version: '3.8'
services:
  combined_app:
    image: rdcs_9sky:0.1
    container_name: rdcs_9sky
    networks:
      - rdcnet9sky
    ports:
      - "4999:4999"
      # - "5001:5001"
      # - "5002:5002"
      # - "5003:5003"
    volumes:
      - ../models/gd:/app/models
    environment:
      - INPUT_DIM=${INPUT_DIM}
      - MODEL_PATH_NAME=${MODEL_PATH_NAME}
      - APP_RD=${APP_RD}
      - APP_CL=${APP_CL}
      - APP_PLOT=${APP_PLOT}

networks:
  rdcnet9sky:
